/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: 1.0
 */
import type {
  CreateOrderCommand,
  CreateOrderItemCommand,
  DeleteOrderItemCommand,
  ProblemDetails,
  ResultOfGuid,
  ResultOfOrderResponse,
  UpdateOrderCommand
} from '.././model';

import { orvalFetch } from '../../orval-fetch';

/**
 * Creates a new order with the specified details.
 * @summary Creates a new order
 */
export type postCreateOrderResponse201 = {
  data: ResultOfGuid
  status: 201
}

export type postCreateOrderResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postCreateOrderResponseSuccess = (postCreateOrderResponse201) & {
  headers: Headers;
};
export type postCreateOrderResponseError = (postCreateOrderResponse400) & {
  headers: Headers;
};

export type postCreateOrderResponse = (postCreateOrderResponseSuccess | postCreateOrderResponseError)

export const getPostCreateOrderUrl = () => {


  

  return `/create-order`
}

export const postCreateOrder = async (createOrderCommand: CreateOrderCommand, options?: RequestInit): Promise<postCreateOrderResponse> => {
  
  return orvalFetch<postCreateOrderResponse>(getPostCreateOrderUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrderCommand,)
  }
);}
  

/**
 * Updates an existing order with the specified ID.
 * @summary Updates an existing order
 */
export type putUpdateOrderResponse204 = {
  data: ResultOfGuid
  status: 204
}

export type putUpdateOrderResponse400 = {
  data: ProblemDetails
  status: 400
}

export type putUpdateOrderResponseSuccess = (putUpdateOrderResponse204) & {
  headers: Headers;
};
export type putUpdateOrderResponseError = (putUpdateOrderResponse400) & {
  headers: Headers;
};

export type putUpdateOrderResponse = (putUpdateOrderResponseSuccess | putUpdateOrderResponseError)

export const getPutUpdateOrderUrl = () => {


  

  return `/update-order`
}

export const putUpdateOrder = async (updateOrderCommand: UpdateOrderCommand, options?: RequestInit): Promise<putUpdateOrderResponse> => {
  
  return orvalFetch<putUpdateOrderResponse>(getPutUpdateOrderUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOrderCommand,)
  }
);}
  

/**
 * Gets an order with the specified ID.
 * @summary Gets an order by ID
 */
export type getGetOrderIdResponse200 = {
  data: ResultOfOrderResponse
  status: 200
}

export type getGetOrderIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getGetOrderIdResponseSuccess = (getGetOrderIdResponse200) & {
  headers: Headers;
};
export type getGetOrderIdResponseError = (getGetOrderIdResponse404) & {
  headers: Headers;
};

export type getGetOrderIdResponse = (getGetOrderIdResponseSuccess | getGetOrderIdResponseError)

export const getGetGetOrderIdUrl = (id: string,) => {


  

  return `/get-order/${id}`
}

export const getGetOrderId = async (id: string, options?: RequestInit): Promise<getGetOrderIdResponse> => {
  
  return orvalFetch<getGetOrderIdResponse>(getGetGetOrderIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Adds an item to an order with the specified details.
 * @summary Adds an item to an order
 */
export type postAddOrderItemResponse201 = {
  data: ResultOfGuid
  status: 201
}

export type postAddOrderItemResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postAddOrderItemResponseSuccess = (postAddOrderItemResponse201) & {
  headers: Headers;
};
export type postAddOrderItemResponseError = (postAddOrderItemResponse400) & {
  headers: Headers;
};

export type postAddOrderItemResponse = (postAddOrderItemResponseSuccess | postAddOrderItemResponseError)

export const getPostAddOrderItemUrl = () => {


  

  return `/add-order-item`
}

export const postAddOrderItem = async (createOrderItemCommand: CreateOrderItemCommand, options?: RequestInit): Promise<postAddOrderItemResponse> => {
  
  return orvalFetch<postAddOrderItemResponse>(getPostAddOrderItemUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrderItemCommand,)
  }
);}
  

/**
 * Removes an item from an order with the specified ID.
 * @summary Removes an item from an order
 */
export type deleteRemoveOrderItemResponse204 = {
  data: ResultOfGuid
  status: 204
}

export type deleteRemoveOrderItemResponse400 = {
  data: ProblemDetails
  status: 400
}

export type deleteRemoveOrderItemResponseSuccess = (deleteRemoveOrderItemResponse204) & {
  headers: Headers;
};
export type deleteRemoveOrderItemResponseError = (deleteRemoveOrderItemResponse400) & {
  headers: Headers;
};

export type deleteRemoveOrderItemResponse = (deleteRemoveOrderItemResponseSuccess | deleteRemoveOrderItemResponseError)

export const getDeleteRemoveOrderItemUrl = () => {


  

  return `/remove-order-item`
}

export const deleteRemoveOrderItem = async (deleteOrderItemCommand: DeleteOrderItemCommand, options?: RequestInit): Promise<deleteRemoveOrderItemResponse> => {
  
  return orvalFetch<deleteRemoveOrderItemResponse>(getDeleteRemoveOrderItemUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deleteOrderItemCommand,)
  }
);}
  

