/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: 1.0
 */
import type {
  CreateBookCommand,
  DeleteBookCommand,
  ProblemDetails,
  ResultOfBookResponse,
  ResultOfGuid,
  UpdateBookCommand
} from '.././model';

import { orvalFetch } from '../../orval-fetch';

/**
 * Creates a new book with the specified title and genre.
 * @summary Creates a new book
 */
export type postCreateBookResponse201 = {
  data: ResultOfGuid
  status: 201
}

export type postCreateBookResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postCreateBookResponseSuccess = (postCreateBookResponse201) & {
  headers: Headers;
};
export type postCreateBookResponseError = (postCreateBookResponse400) & {
  headers: Headers;
};

export type postCreateBookResponse = (postCreateBookResponseSuccess | postCreateBookResponseError)

export const getPostCreateBookUrl = () => {


  

  return `/create-book`
}

export const postCreateBook = async (createBookCommand: CreateBookCommand, options?: RequestInit): Promise<postCreateBookResponse> => {
  
  return orvalFetch<postCreateBookResponse>(getPostCreateBookUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createBookCommand,)
  }
);}
  

/**
 * Updates an existing book with the specified ID.
 * @summary Updates an existing book
 */
export type putUpdateBookResponse204 = {
  data: ResultOfGuid
  status: 204
}

export type putUpdateBookResponse400 = {
  data: ProblemDetails
  status: 400
}

export type putUpdateBookResponseSuccess = (putUpdateBookResponse204) & {
  headers: Headers;
};
export type putUpdateBookResponseError = (putUpdateBookResponse400) & {
  headers: Headers;
};

export type putUpdateBookResponse = (putUpdateBookResponseSuccess | putUpdateBookResponseError)

export const getPutUpdateBookUrl = () => {


  

  return `/update-book`
}

export const putUpdateBook = async (updateBookCommand: UpdateBookCommand, options?: RequestInit): Promise<putUpdateBookResponse> => {
  
  return orvalFetch<putUpdateBookResponse>(getPutUpdateBookUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateBookCommand,)
  }
);}
  

/**
 * Deletes an existing book with the specified ID.
 * @summary Deletes an existing book
 */
export type deleteDeleteBookResponse204 = {
  data: ResultOfGuid
  status: 204
}

export type deleteDeleteBookResponse400 = {
  data: ProblemDetails
  status: 400
}

export type deleteDeleteBookResponseSuccess = (deleteDeleteBookResponse204) & {
  headers: Headers;
};
export type deleteDeleteBookResponseError = (deleteDeleteBookResponse400) & {
  headers: Headers;
};

export type deleteDeleteBookResponse = (deleteDeleteBookResponseSuccess | deleteDeleteBookResponseError)

export const getDeleteDeleteBookUrl = () => {


  

  return `/delete-book`
}

export const deleteDeleteBook = async (deleteBookCommand: DeleteBookCommand, options?: RequestInit): Promise<deleteDeleteBookResponse> => {
  
  return orvalFetch<deleteDeleteBookResponse>(getDeleteDeleteBookUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deleteBookCommand,)
  }
);}
  

/**
 * Gets a book with the specified ID.
 * @summary Gets a book by ID
 */
export type getGetBookIdResponse200 = {
  data: ResultOfBookResponse
  status: 200
}

export type getGetBookIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getGetBookIdResponseSuccess = (getGetBookIdResponse200) & {
  headers: Headers;
};
export type getGetBookIdResponseError = (getGetBookIdResponse404) & {
  headers: Headers;
};

export type getGetBookIdResponse = (getGetBookIdResponseSuccess | getGetBookIdResponseError)

export const getGetGetBookIdUrl = (id: string,) => {


  

  return `/get-book/${id}`
}

export const getGetBookId = async (id: string, options?: RequestInit): Promise<getGetBookIdResponse> => {
  
  return orvalFetch<getGetBookIdResponse>(getGetGetBookIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Gets all books without pagination
 * @summary Gets all books
 */
export type getGetBooksResponse200 = {
  data: ResultOfBookResponse
  status: 200
}

export type getGetBooksResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getGetBooksResponseSuccess = (getGetBooksResponse200) & {
  headers: Headers;
};
export type getGetBooksResponseError = (getGetBooksResponse404) & {
  headers: Headers;
};

export type getGetBooksResponse = (getGetBooksResponseSuccess | getGetBooksResponseError)

export const getGetGetBooksUrl = () => {


  

  return `/get-books`
}

export const getGetBooks = async ( options?: RequestInit): Promise<getGetBooksResponse> => {
  
  return orvalFetch<getGetBooksResponse>(getGetGetBooksUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

