/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateBookCommand,
  ProblemDetails,
  ResultOfBookResponse,
  ResultOfGuid,
  ResultOfIEnumerableOfBookResponse,
  UpdateBookCommand
} from '.././model';

import { orvalFetch } from '../../orval-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a new book with the specified title and genre.
 * @summary Creates a new book
 */
export type postApiV1BooksResponse201 = {
  data: ResultOfGuid
  status: 201
}

export type postApiV1BooksResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postApiV1BooksResponseSuccess = (postApiV1BooksResponse201) & {
  headers: Headers;
};
export type postApiV1BooksResponseError = (postApiV1BooksResponse400) & {
  headers: Headers;
};

export type postApiV1BooksResponse = (postApiV1BooksResponseSuccess | postApiV1BooksResponseError)

export const getPostApiV1BooksUrl = () => {


  

  return `/api/v1/books`
}

export const postApiV1Books = async (createBookCommand: CreateBookCommand, options?: RequestInit): Promise<postApiV1BooksResponse> => {
  
  return orvalFetch<postApiV1BooksResponse>(getPostApiV1BooksUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createBookCommand,)
  }
);}
  



export const getPostApiV1BooksMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Books>>, TError,{data: CreateBookCommand}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Books>>, TError,{data: CreateBookCommand}, TContext> => {

const mutationKey = ['postApiV1Books'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Books>>, {data: CreateBookCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Books(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1BooksMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Books>>>
    export type PostApiV1BooksMutationBody = CreateBookCommand
    export type PostApiV1BooksMutationError = ProblemDetails

    /**
 * @summary Creates a new book
 */
export const usePostApiV1Books = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Books>>, TError,{data: CreateBookCommand}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Books>>,
        TError,
        {data: CreateBookCommand},
        TContext
      > => {
      return useMutation(getPostApiV1BooksMutationOptions(options), queryClient);
    }
    /**
 * Gets all books without pagination
 * @summary Gets all books
 */
export type getApiV1BooksResponse200 = {
  data: ResultOfIEnumerableOfBookResponse
  status: 200
}

export type getApiV1BooksResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getApiV1BooksResponseSuccess = (getApiV1BooksResponse200) & {
  headers: Headers;
};
export type getApiV1BooksResponseError = (getApiV1BooksResponse404) & {
  headers: Headers;
};

export type getApiV1BooksResponse = (getApiV1BooksResponseSuccess | getApiV1BooksResponseError)

export const getGetApiV1BooksUrl = () => {


  

  return `/api/v1/books`
}

export const getApiV1Books = async ( options?: RequestInit): Promise<getApiV1BooksResponse> => {
  
  return orvalFetch<getApiV1BooksResponse>(getGetApiV1BooksUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetApiV1BooksQueryKey = () => {
    return [
    `/api/v1/books`
    ] as const;
    }

    
export const getGetApiV1BooksQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Books>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BooksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Books>>> = ({ signal }) => getApiV1Books({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BooksQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Books>>>
export type GetApiV1BooksQueryError = ProblemDetails


export function useGetApiV1Books<TData = Awaited<ReturnType<typeof getApiV1Books>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Books>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Books>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Books<TData = Awaited<ReturnType<typeof getApiV1Books>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Books>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Books>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Books<TData = Awaited<ReturnType<typeof getApiV1Books>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Gets all books
 */

export function useGetApiV1Books<TData = Awaited<ReturnType<typeof getApiV1Books>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BooksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Updates an existing book with the specified ID.
 * @summary Updates an existing book
 */
export type putApiV1BooksIdResponse204 = {
  data: void
  status: 204
}

export type putApiV1BooksIdResponse400 = {
  data: ProblemDetails
  status: 400
}

export type putApiV1BooksIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type putApiV1BooksIdResponseSuccess = (putApiV1BooksIdResponse204) & {
  headers: Headers;
};
export type putApiV1BooksIdResponseError = (putApiV1BooksIdResponse400 | putApiV1BooksIdResponse404) & {
  headers: Headers;
};

export type putApiV1BooksIdResponse = (putApiV1BooksIdResponseSuccess | putApiV1BooksIdResponseError)

export const getPutApiV1BooksIdUrl = (id: string,) => {


  

  return `/api/v1/books/${id}`
}

export const putApiV1BooksId = async (id: string,
    updateBookCommand: UpdateBookCommand, options?: RequestInit): Promise<putApiV1BooksIdResponse> => {
  
  return orvalFetch<putApiV1BooksIdResponse>(getPutApiV1BooksIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateBookCommand,)
  }
);}
  



export const getPutApiV1BooksIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1BooksId>>, TError,{id: string;data: UpdateBookCommand}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1BooksId>>, TError,{id: string;data: UpdateBookCommand}, TContext> => {

const mutationKey = ['putApiV1BooksId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1BooksId>>, {id: string;data: UpdateBookCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1BooksId(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1BooksIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1BooksId>>>
    export type PutApiV1BooksIdMutationBody = UpdateBookCommand
    export type PutApiV1BooksIdMutationError = ProblemDetails

    /**
 * @summary Updates an existing book
 */
export const usePutApiV1BooksId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1BooksId>>, TError,{id: string;data: UpdateBookCommand}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1BooksId>>,
        TError,
        {id: string;data: UpdateBookCommand},
        TContext
      > => {
      return useMutation(getPutApiV1BooksIdMutationOptions(options), queryClient);
    }
    /**
 * Deletes an existing book with the specified ID.
 * @summary Deletes an existing book
 */
export type deleteApiV1BooksIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiV1BooksIdResponse400 = {
  data: ProblemDetails
  status: 400
}

export type deleteApiV1BooksIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type deleteApiV1BooksIdResponseSuccess = (deleteApiV1BooksIdResponse204) & {
  headers: Headers;
};
export type deleteApiV1BooksIdResponseError = (deleteApiV1BooksIdResponse400 | deleteApiV1BooksIdResponse404) & {
  headers: Headers;
};

export type deleteApiV1BooksIdResponse = (deleteApiV1BooksIdResponseSuccess | deleteApiV1BooksIdResponseError)

export const getDeleteApiV1BooksIdUrl = (id: string,) => {


  

  return `/api/v1/books/${id}`
}

export const deleteApiV1BooksId = async (id: string, options?: RequestInit): Promise<deleteApiV1BooksIdResponse> => {
  
  return orvalFetch<deleteApiV1BooksIdResponse>(getDeleteApiV1BooksIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteApiV1BooksIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1BooksId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1BooksId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1BooksId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1BooksId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1BooksId(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1BooksIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1BooksId>>>
    
    export type DeleteApiV1BooksIdMutationError = ProblemDetails

    /**
 * @summary Deletes an existing book
 */
export const useDeleteApiV1BooksId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1BooksId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1BooksId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiV1BooksIdMutationOptions(options), queryClient);
    }
    /**
 * Gets a book with the specified ID.
 * @summary Gets a book by ID
 */
export type getApiV1BooksIdResponse200 = {
  data: ResultOfBookResponse
  status: 200
}

export type getApiV1BooksIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getApiV1BooksIdResponseSuccess = (getApiV1BooksIdResponse200) & {
  headers: Headers;
};
export type getApiV1BooksIdResponseError = (getApiV1BooksIdResponse404) & {
  headers: Headers;
};

export type getApiV1BooksIdResponse = (getApiV1BooksIdResponseSuccess | getApiV1BooksIdResponseError)

export const getGetApiV1BooksIdUrl = (id: string,) => {


  

  return `/api/v1/books/${id}`
}

export const getApiV1BooksId = async (id: string, options?: RequestInit): Promise<getApiV1BooksIdResponse> => {
  
  return orvalFetch<getApiV1BooksIdResponse>(getGetApiV1BooksIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetApiV1BooksIdQueryKey = (id: string,) => {
    return [
    `/api/v1/books/${id}`
    ] as const;
    }

    
export const getGetApiV1BooksIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BooksId>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BooksIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BooksId>>> = ({ signal }) => getApiV1BooksId(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BooksIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BooksId>>>
export type GetApiV1BooksIdQueryError = ProblemDetails


export function useGetApiV1BooksId<TData = Awaited<ReturnType<typeof getApiV1BooksId>>, TError = ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BooksId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BooksId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BooksId<TData = Awaited<ReturnType<typeof getApiV1BooksId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BooksId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BooksId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BooksId<TData = Awaited<ReturnType<typeof getApiV1BooksId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Gets a book by ID
 */

export function useGetApiV1BooksId<TData = Awaited<ReturnType<typeof getApiV1BooksId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BooksIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




