/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


/**
 * Creates a new book with the specified title and genre.
 * @summary Creates a new book
 */
export const postApiV1BooksBodyTitleMin = 3;
export const postApiV1BooksBodyTitleMax = 200;

export const postApiV1BooksBodyGenreMax = 2;



export const PostApiV1BooksBody = zod.object({
  "title": zod.string().min(postApiV1BooksBodyTitleMin).max(postApiV1BooksBodyTitleMax),
  "genre": zod.string().min(1).max(postApiV1BooksBodyGenreMax)
})

/**
 * Gets all books without pagination
 * @summary Gets all books
 */
export const getApiV1BooksResponseErrorsItemLineNumberDefaultOne = 0;
export const getApiV1BooksResponseErrorsItemLineNumberRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const getApiV1BooksResponseErrorsItemLineNumberDefaultTwo = 0;
export const getApiV1BooksResponseErrorsItemLineNumberRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const getApiV1BooksResponseErrorsItemLineNumberDefault = 0;
export const getApiV1BooksResponseErrorsItemMemberNameDefault = ``;
export const getApiV1BooksResponseErrorsItemFilePathDefault = ``;

export const GetApiV1BooksResponse = zod.object({
  "value": zod.array(zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "genre": zod.string()
})).nullish(),
  "isSuccess": zod.boolean().optional(),
  "errors": zod.array(zod.object({
  "message": zod.string(),
  "code": zod.string().nullish(),
  "lineNumber": zod.union([zod.number().default(getApiV1BooksResponseErrorsItemLineNumberDefaultOne),zod.number().default(getApiV1BooksResponseErrorsItemLineNumberDefaultTwo)]).optional(),
  "memberName": zod.string().default(getApiV1BooksResponseErrorsItemMemberNameDefault),
  "filePath": zod.string().default(getApiV1BooksResponseErrorsItemFilePathDefault)
})).optional()
})

/**
 * Updates an existing book with the specified ID.
 * @summary Updates an existing book
 */
export const PutApiV1BooksIdParams = zod.object({
  "id": zod.uuid()
})

export const putApiV1BooksIdBodyTitleMin = 3;
export const putApiV1BooksIdBodyTitleMax = 200;

export const putApiV1BooksIdBodyGenreMax = 2;



export const PutApiV1BooksIdBody = zod.object({
  "id": zod.uuid(),
  "title": zod.string().min(putApiV1BooksIdBodyTitleMin).max(putApiV1BooksIdBodyTitleMax),
  "genre": zod.string().min(1).max(putApiV1BooksIdBodyGenreMax)
})

/**
 * Deletes an existing book with the specified ID.
 * @summary Deletes an existing book
 */
export const DeleteApiV1BooksIdParams = zod.object({
  "id": zod.uuid()
})

/**
 * Gets a book with the specified ID.
 * @summary Gets a book by ID
 */
export const GetApiV1BooksIdParams = zod.object({
  "id": zod.uuid()
})

export const getApiV1BooksIdResponseErrorsItemLineNumberDefaultOne = 0;
export const getApiV1BooksIdResponseErrorsItemLineNumberRegExpOne = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const getApiV1BooksIdResponseErrorsItemLineNumberDefaultTwo = 0;
export const getApiV1BooksIdResponseErrorsItemLineNumberRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const getApiV1BooksIdResponseErrorsItemLineNumberDefault = 0;
export const getApiV1BooksIdResponseErrorsItemMemberNameDefault = ``;
export const getApiV1BooksIdResponseErrorsItemFilePathDefault = ``;

export const GetApiV1BooksIdResponse = zod.object({
  "value": zod.union([zod.null(),zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "genre": zod.string()
})]).optional(),
  "isSuccess": zod.boolean().optional(),
  "errors": zod.array(zod.object({
  "message": zod.string(),
  "code": zod.string().nullish(),
  "lineNumber": zod.union([zod.number().default(getApiV1BooksIdResponseErrorsItemLineNumberDefaultOne),zod.number().default(getApiV1BooksIdResponseErrorsItemLineNumberDefaultTwo)]).optional(),
  "memberName": zod.string().default(getApiV1BooksIdResponseErrorsItemMemberNameDefault),
  "filePath": zod.string().default(getApiV1BooksIdResponseErrorsItemFilePathDefault)
})).optional()
})

