/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: 1.0
 */

export interface CreateOrderCommand {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  customerId: number | string;
}
