/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: v1
 */

export interface Error {
  message: string;
  /** @nullable */
  code?: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  lineNumber?: number | string;
  memberName?: string;
  filePath?: string;
}
