/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: v1
 */

export type GetApiV1BooksParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};
