/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: 1.0
 */
import type { OrderItemResponse } from './orderItemResponse';

export interface OrderResponse {
  id: string;
  customerName: string;
  orderStatus: string;
  orderItems: OrderItemResponse[];
}
