/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: 1.0
 */

export interface OrderItemResponse {
  bookName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  quantity: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  price: number | string;
}
