/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: v1
 */
import type { Error } from './error';
import type { PaginatedResponseOfBookResponse } from './paginatedResponseOfBookResponse';

export interface ResultOfPaginatedResponseOfBookResponse {
  value?: null | PaginatedResponseOfBookResponse;
  isSuccess?: boolean;
  errors?: Error[];
}
