/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: 1.0
 */
import type { Error } from './error';
import type { OrderResponse } from './orderResponse';

export interface ResultOfOrderResponse {
  value?: null | OrderResponse;
  isSuccess?: boolean;
  errors?: Error[];
}
