/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: v1
 */
import type { Error } from './error';

export interface ResultOfGuid {
  value?: string;
  isSuccess?: boolean;
  errors?: Error[];
}
