/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: 1.0
 */
import type { BookResponse } from './bookResponse';
import type { Error } from './error';

export interface ResultOfBookResponse {
  value?: null | BookResponse;
  isSuccess?: boolean;
  errors?: Error[];
}
