/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: v1
 */

export interface UpdateBookCommand {
  id: string;
  title: string;
  genre: string;
}
