/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: 1.0
 */

export interface UpdateOrderCommand {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  orderId: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  orderStatus: number | string;
}
