/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clean Architecture API
 * OpenAPI spec version: v1
 */

export interface UpdateBookCommand {
  id: string;
  /**
   * @minLength 3
   * @maxLength 200
   */
  title: string;
  /**
   * @minLength 1
   * @maxLength 2
   */
  genre: string;
}
