//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Domain.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BookErrors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookErrors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CleanArchitecture.Domain.Resources.BookErrors", typeof(BookErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Book_TitleIsRequired {
            get {
                return ResourceManager.GetString("Book.TitleIsRequired", resourceCulture);
            }
        }
        
        public static string Book_TitleTooLong {
            get {
                return ResourceManager.GetString("Book.TitleTooLong", resourceCulture);
            }
        }
        
        public static string Book_InvalidGenre {
            get {
                return ResourceManager.GetString("Book.InvalidGenre", resourceCulture);
            }
        }
        
        public static string Book_NotFound {
            get {
                return ResourceManager.GetString("Book.NotFound", resourceCulture);
            }
        }
        
        public static string Book_TitleIsTooShort {
            get {
                return ResourceManager.GetString("Book.TitleIsTooShort", resourceCulture);
            }
        }
        
        public static string Book_GenreIsRequired {
            get {
                return ResourceManager.GetString("Book.GenreIsRequired", resourceCulture);
            }
        }
        
        public static string Book_GenreIsInvalidLength {
            get {
                return ResourceManager.GetString("Book.GenreIsInvalidLength", resourceCulture);
            }
        }
    }
}
